### ISSUE TITLE
FTP Client says connected and not getting an FTP shell

### ISSUE THREAD

**Issue by jamesattard** [adispataru/maroodi#1]
Followed instructions and FTP client is not getting an FTP Shell. Is this project broken?

**Comment by adispataru** [comment]
Haven't made us of it lately. If there is no error in the server console, then it must be a client problem. Are you using SFTP? what client are you using? My team tested using filezilla and it was working.

**Comment by jamesattard** [comment]
default Linux ftp client. Additionally, when executing the jar file it seems that the connection is regular FTP on port 21.

**Comment by adispataru** [comment]
Sorry, I meant FTPS (FTP over SSL/TLS). Eventually you can try **ftps**://yourdomain.com, or try to force the client to use FTPS.

**Comment by jamesattard** [comment]
You are right, this works with FTPS (not SFTP)! Is there a way to change the default port from 21 to something else?

**Comment by adispataru** [comment]
You can uncomment and edit line 85 in [App.java](https://github.com/adispataru/maroodi/blob/master/src/main/java/eu/scape_project/HDFSFTPServer/main/App.java) to choose the desired port. Then `mvn package` again.
